"""create_hourly_metrics_and_rejected_logs

Revision ID: 18c339a784e2
Revises: 
Create Date: 2026-03-02 09:00:45.175038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c339a784e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly_metrics',
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('status_category', sa.String(length=10), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_response_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('p95_response_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.String(length=10), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('window_start', 'endpoint', 'status_category')
    )
    op.create_index('idx_metrics_endpoint', 'hourly_metrics', ['endpoint'], unique=False)
    op.create_index('idx_metrics_window', 'hourly_metrics', ['window_start'], unique=False)
    op.create_table('rejected_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=200), nullable=False),
    sa.Column('log_date', sa.String(length=10), nullable=False),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected_logs')
    op.drop_index('idx_metrics_window', table_name='hourly_metrics')
    op.drop_index('idx_metrics_endpoint', table_name='hourly_metrics')
    op.drop_table('hourly_metrics')
    # ### end Alembic commands ###
