"""add_top_ips_table

Revision ID: 7dba19183e4b
Revises: dd7ae0c626b3
Create Date: 2026-03-03 10:27:14.347788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dba19183e4b'
down_revision: Union[str, Sequence[str], None] = 'dd7ae0c626b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_ips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('unique_endpoints', sa.Integer(), nullable=False),
    sa.Column('avg_response_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('log_date', sa.String(length=10), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_top_ips_date', 'top_ips', ['log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_top_ips_date', table_name='top_ips')
    op.drop_table('top_ips')
    # ### end Alembic commands ###
