"""create_hourly_metrics_and_rejected_logs

Revision ID: dd7ae0c626b3
Revises: 18c339a784e2
Create Date: 2026-03-02 09:05:55.311185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7ae0c626b3'
down_revision: Union[str, Sequence[str], None] = '18c339a784e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
